In [288]:
import pandas as pd 
import numpy as np 

In [289]:
# spam data chinese
spam_data1 = pd.read_csv('category/ham_train.txt', delimiter= '\t')
spam_data1.columns = ["Text"]
print(spam_data1.head())
print(len(spam_data1))

                                                Text
0                          便 宜 又 适 用 ， 也 非 常 容 易 撕 掉
1  质 量 跟 我 预 想 的 差 不 多 ， 布 料 很 薄 ， 说 不 上 有 没 有 色 ...
2                    好 评 应 该 有 八 十 五 字 了 吧 ， 涨 淘 气 值
3                          第 二 双 ， 超 级 棒 ， 上 脚 很 好 看
4                差 ， 去 日 本 无 服 务 ， 耽 误 了 一 天 半 时 间 呵
19999


In [290]:
spam_data1['Category'] = 0
spam_data1.head()

Text  Category
0                          便 宜 又 适 用 ， 也 非 常 容 易 撕 掉         0
1  质 量 跟 我 预 想 的 差 不 多 ， 布 料 很 薄 ， 说 不 上 有 没 有 色 ...         0
2                    好 评 应 该 有 八 十 五 字 了 吧 ， 涨 淘 气 值         0
3                          第 二 双 ， 超 级 棒 ， 上 脚 很 好 看         0
4                差 ， 去 日 本 无 服 务 ， 耽 误 了 一 天 半 时 间 呵         0

In [291]:
# spam_data1['Category'] = spam_data1['Category'].astype(int)
# spam_data1.head()

In [292]:
# spam_data2 = pd.read_csv('category/ham_test.txt', delimiter= '\t')
# spam_data2.columns = ["Text"]
# print(spam_data2.head())
# print(len(spam_data2))

In [293]:
# spam_data2['Category'] = 0
# spam_data2.head()

In [294]:
spam_data3 = pd.read_csv('category/spam_train.txt', delimiter= '\t')
spam_data3.columns = ["Text"]
print(spam_data3.head())
print(len(spam_data3))

                                                Text
0  我 日 你 妈 妈 耶   龟 儿 子 蟑 螂 都 搞 起 来 了     这 么 好 奶 ...
1                          骑 手 态 度 恶 劣 ， 吓 人 ， 想 艹 他
2  十 四 块 的 七 虾 卷   艹 你 妈 的 里 面 什 么 都 没 有 光 吃 外 面 ...
3  我 艹 ， 你 做 的 这 是 啥 几 把 东 西 啊 ， 还 尼 玛 酸 的 ， 我 操 ...
4                                      太 咸 了 我 操 ！ ！
17298


In [295]:
spam_data3['Category'] = 1
spam_data3.head()

Text  Category
0  我 日 你 妈 妈 耶   龟 儿 子 蟑 螂 都 搞 起 来 了     这 么 好 奶 ...         1
1                          骑 手 态 度 恶 劣 ， 吓 人 ， 想 艹 他         1
2  十 四 块 的 七 虾 卷   艹 你 妈 的 里 面 什 么 都 没 有 光 吃 外 面 ...         1
3  我 艹 ， 你 做 的 这 是 啥 几 把 东 西 啊 ， 还 尼 玛 酸 的 ， 我 操 ...         1
4                                      太 咸 了 我 操 ！ ！         1

In [296]:
# spam_data3['Category'] = spam_data3['Category'].astype(int)
# spam_data3.head()

In [297]:
# spam_data4 = pd.read_csv('category/spam_test.txt', delimiter= '\t')
# spam_data4.columns = ["Text"]
# print(spam_data4.head())
# print(len(spam_data4))

In [298]:
# spam_data4['Category'] = 1
# spam_data4.head()

In [312]:
# Combine all dataframes into one master dataframe
spam_data = pd.concat([spam_data1, spam_data3], ignore_index = True)
print(spam_data.head())
print(len(spam_data))
spam_data['Category'] = spam_data['Category'].astype(int)
spam_data.head()

                                                Text  Category
0                          便 宜 又 适 用 ， 也 非 常 容 易 撕 掉         0
1  质 量 跟 我 预 想 的 差 不 多 ， 布 料 很 薄 ， 说 不 上 有 没 有 色 ...         0
2                    好 评 应 该 有 八 十 五 字 了 吧 ， 涨 淘 气 值         0
3                          第 二 双 ， 超 级 棒 ， 上 脚 很 好 看         0
4                差 ， 去 日 本 无 服 务 ， 耽 误 了 一 天 半 时 间 呵         0
37297


Text  Category
0                          便 宜 又 适 用 ， 也 非 常 容 易 撕 掉         0
1  质 量 跟 我 预 想 的 差 不 多 ， 布 料 很 薄 ， 说 不 上 有 没 有 色 ...         0
2                    好 评 应 该 有 八 十 五 字 了 吧 ， 涨 淘 气 值         0
3                          第 二 双 ， 超 级 棒 ， 上 脚 很 好 看         0
4                差 ， 去 日 本 无 服 务 ， 耽 误 了 一 天 半 时 间 呵         0

In [313]:
spam_data['Category'].value_counts()

0    19999
1    17298
Name: Category, dtype: int64

In [314]:
# spam_data = spam_data.dropna(axis = 0, how ='any')
# len(spam_data)

In [315]:
# spam_data.to_csv('spam_data_chinese_sm.csv', index=False)

In [316]:
# new_data = pd.read_csv('spam_data_chinese_sm.csv')
# new_data.head()

In [317]:
# len(new_data)

In [318]:
# spam_data = pd.read_csv("category/CHINESE_SENTIMENT_TRAIN_COMBINED.csv",nrows=30000)
# spam_data.head()

In [319]:
# spam_data['label'].value_counts()

In [320]:
# spam_data.rename(columns = {'text': 'Text'}, inplace = True)
# spam_data.rename(columns = {'label': 'Category'}, inplace = True)

In [321]:
spam_data = spam_data.dropna(axis = 0, how ='any')
len(spam_data)

37297

In [322]:
# from spacy.lang.en.stop_words import STOP_WORDS
import stopwordsiso as sw
from collections import Counter
import string
import spacy
import re
from zhon.hanzi import non_stops, stops
import jieba.posseg as pseg

punctuation_auto = list(string.punctuation)
punctuation_ch = list(stops+non_stops)
punctuation_custom = [ '...', '…' ]
punctuation = np.unique(punctuation_auto+punctuation_ch+punctuation_custom)

stop_words = list(sw.stopwords(["zh"]))
stop_words_custom = ['kau', 'yg', 'mcm', 'gak', 'nak', 'ni', 'tu', 'la', 'je', 'kat', 'ya', 'dgn', 'tau', 'org', 'rt', 'aja', 'nk', 'dah',
                        'orang', 'sy', 'ga', 'kalo', 'kena']
STOP_WORDS = np.unique(stop_words+stop_words_custom)

def text_cleaning_chinese(text):
    
    text= text.replace(" ", "")

    words = pseg.cut(text)
    cleaned_tokens = []
    for w in words:
        if w.word not in list(STOP_WORDS) and w.word not in list(punctuation):
            cleaned_tokens.append(w.word)

    complete_sentence = ' '.join([str(words) for words in cleaned_tokens])

    return complete_sentence

# def light_text_cleaning(text):
#     text = text.lower()
#     text = re.sub('\[.*?\]', '', text)
#     # text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
#     text = re.sub('\w*\d\w*', '', text)
#     text = re.sub('[‘’“”…]', '', text)
#     text = re.sub('\n', '', text)

#     # remove numbers
#     text = re.sub(r'[0-9]', '', text)
#     # remove links
#     text = re.sub('http[s]?://\S+', '', text)
#     # remove word with tweethandle @name
#     text = re.sub('[^ ]*@[^ ]*', '', text)
#     # remove [emoji]
#     text = re.sub('\[(.*?)\]', '', text)

#     # remove punctuation, stopwords
#     tokens = text.split()
#     cleaned_tokens = []
#     for word in tokens:
#         if word not in list(STOP_WORDS) and word not in list(punctuation):
#             cleaned_tokens.append(word)

#     complete_sentence = ' '.join([str(words) for words in cleaned_tokens])

#     return complete_sentence

# def text_cleaning_english(text,mynlp):

#     # remove numbers
#     text = re.sub(r'\d+', '', text)
#     # remove links
#     text = re.sub('http[s]?://\S+', '', text)
#     # remove word with tweethandle @name
#     text = re.sub('[^ ]*@[^ ]*', '', text)

#     doc = mynlp(text)
    
#     # Lemmatization
#     tokens = []
#     for token in doc:
#         if token.lemma_ != "-PRON-":
#             temp = token.lemma_.lower().strip()
#         else:
#             temp = token.lower_
#         tokens.append(temp)
    
#     # Remove punctuation and stopwords
#     cleaned_tokens = []
#     for token in tokens:
#         if token not in list(STOP_WORDS) and token not in punctuation:
#             cleaned_tokens.append(token)

#     # traverse in the string     
#     complete_sentence = ' '.join([str(words) for words in cleaned_tokens])

#     return complete_sentence

In [323]:
# text = '南 元 侈 ， 实 计 上 世 哦 蜀 斯 入 不 入 算 供 货 了 ， 布 他 们 为 了 可 联 复 面 已 ， 先 襄 襄 羊 不 买 了 ！ 南 他 如 复 霸 仅 新 太 体 现 临 离 进 至 卧'

# test = text_cleaning_chinese(text)
# test

In [324]:
text_cleaning = lambda x: text_cleaning_chinese(x)
spam_data['Cleaned_Text'] = pd.DataFrame(spam_data['Text'].apply(text_cleaning))

In [325]:
# SPLIT TRAINING & TESTING DATA
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(spam_data['Cleaned_Text'],spam_data['Category'],test_size=0.2,shuffle=True, random_state=42)
print(X_train.shape, y_train.shape)

(29837,) (29837,)


In [326]:
X_train.head()

31800                 哈哈哈 傻子
6594     好极了 太好了 无法 言语 形容 太值
14880         家具 满意 小九 服务 五分
11839               桌子 买高 满意
460            老板 家 贝珠 质量 不错
Name: Cleaned_Text, dtype: object

In [327]:
y_train.head()

31800    1
6594     0
14880    0
11839    0
460      0
Name: Category, dtype: int32

In [328]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC 
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score, precision_score, f1_score, recall_score

def sentiment_pipeline(data_train_input,data_train_target,model_type):
    # Classifier selection
    if model_type == "linear":
        classifier = LinearSVC()
    elif model_type == "logistic":
        classifier = LogisticRegression(max_iter=1000)
    elif model_type == "sgd":
        classifier = SGDClassifier()
    elif model_type == "naive_bayes":
        classifier = MultinomialNB()
    elif model_type == "xgboost":
        classifier = XGBClassifier(use_label_encoder=False,eta=0.1,gamma=0.3, n_estimators=100, learning_rate=0.5, min_child_weight=5, 
        max_depth=5, colsample_bytree=0.7,objective="binary:logistic", eval_metric="logloss",verbosity=0)

    tfidf = TfidfVectorizer()

    # Pipeline setup
    clf = Pipeline([('tfidf', tfidf), ('clf', classifier)])

    model = clf.fit(data_train_input,data_train_target)

    return model

def sentiment_model_predict(model,data_test_input,data_test_target):
    data_prediction=model.predict(data_test_input)
    conf_matrix = confusion_matrix(data_test_target,data_prediction)
    acc_score = accuracy_score(data_test_target, data_prediction)
    pre_score = precision_score(data_test_target, data_prediction, average="macro")
    re_score = recall_score(data_test_target, data_prediction, average="macro")
    f_score = f1_score(data_test_target, data_prediction, average="macro")

    print("Accuracy : "+str(round(acc_score*100,2)))
    print("Precision : "+str(round(pre_score*100,2)))
    print("Recall : "+str(round(re_score*100,2)))
    print("F1-Score :"+str(round(f_score*100,2)))
    print(conf_matrix)

In [329]:
# Support Vector Classification
svm_model = sentiment_pipeline(X_train, y_train, 'linear')
sentiment_model_predict(svm_model,X_test,y_test)

Accuracy : 93.54
Precision : 93.49
Recall : 93.63
F1-Score :93.53
[[3650  310]
 [ 172 3328]]


In [330]:
xg_model = sentiment_pipeline(X_train, y_train, 'xgboost')
sentiment_model_predict(xg_model,X_test,y_test)

Accuracy : 88.71
Precision : 89.08
Recall : 89.06
F1-Score :88.71
[[3303  657]
 [ 185 3315]]


In [331]:
nb_model = sentiment_pipeline(X_train, y_train, 'naive_bayes')
sentiment_model_predict(nb_model,X_test,y_test)

Accuracy : 90.71
Precision : 91.7
Recall : 90.26
F1-Score :90.55
[[3863   97]
 [ 596 2904]]


In [332]:
lg_model = sentiment_pipeline(X_train, y_train, 'logistic')
sentiment_model_predict(lg_model,X_test,y_test)

Accuracy : 93.31
Precision : 93.3
Recall : 93.46
F1-Score :93.3
[[3606  354]
 [ 145 3355]]


In [333]:
sgd_model = sentiment_pipeline(X_train, y_train, 'sgd')
sentiment_model_predict(sgd_model,X_test,y_test)

Accuracy : 92.88
Precision : 92.91
Recall : 93.07
F1-Score :92.88
[[3565  395]
 [ 136 3364]]


In [343]:
# save model
import joblib

# Save RL_Model to file in the current working directory
joblib.dump(svm_model, "spam_svm_chinese_model.pkl")
joblib.dump(xg_model, "spam_xg_chinese_model.pkl")
joblib.dump(nb_model, "spam_nb_chinese_model.pkl")
joblib.dump(lg_model, "spam_lg_chinese_model.pkl")
joblib.dump(sgd_model, "spam_sgd_chinese_model.pkl")

['spam_sgd_chinese_model.pkl']

In [ ]:
import pandas as pd 
import numpy as np 
import joblib 

# load model
joblib_SVM_model = joblib.load("model/spam_svm_chinese_model.pkl")
sentiment_model_predict(joblib_SVM_model,X_test,y_test)

In [338]:
test_ham = pd.read_csv('category/ham_test.txt', delimiter= '\t')
test_ham.columns = ["Text"]
print(test_ham.head())

                                                Text
0                                才 买 了 没 好 久 就 降 价 了
1  是 假 货 ， 味 道 一 点 也 不 好 ， 赚 黑 钱 的 ， 亲 们 千 万 别 买 ...
2                杆 子 是 干 大 物 滴 … … 这 个 价 位 里 … 很 牛 逼
3                                        款 式 简 单 舒 适
4                                        真 的 灰 常 好 看


In [339]:
test_spam = pd.read_csv('category/spam_test.txt', delimiter= '\t')
test_spam.columns = ["Text"]
print(test_spam.head())

                                                Text
0                                      图 腾 ？ ？ ？ 狗 尼
1                      到 处 视 始 的 宝 家 有 啥 式 好 旗 由 的 ？
2                                  杀 马 持 创 使 人   给 给
3  南 元 侈 ， 实 计 上 世 哦 蜀 斯 入 不 入 算 供 货 了 ， 布 他 们 为 ...
4  这 人 写 的 未 息 ， 又 俱 右 长 。 没 有 直 才 卖 学 ， 六 惠 准 六 官 ！


In [340]:
text_cleaning = lambda x: text_cleaning_chinese(x)
test_ham['Cleaned_Text'] = pd.DataFrame(test_ham['Text'].apply(text_cleaning))
test_spam['Cleaned_Text'] = pd.DataFrame(test_spam['Text'].apply(text_cleaning))

In [341]:
pred_data = svm_model.predict(test_ham['Cleaned_Text'])
test_ham['Predicted'] = pred_data
test_ham['Predicted'].value_counts()

0    18416
1     1583
Name: Predicted, dtype: int64

In [342]:
pred_data = svm_model.predict(test_spam['Cleaned_Text'])
test_spam['Predicted'] = pred_data
test_spam['Predicted'].value_counts()

1    15250
0     2048
Name: Predicted, dtype: int64

In [ ]:
test_ham1 = pd.read_csv('category/cleaned_ham_chinese.txt', delimiter= '\t')
test_ham1.columns = ["Text"]
print(test_ham1.head())

In [ ]:
test_spam1 = pd.read_csv('category/cleaned_spam_chinese.txt', delimiter= '\t')
test_spam1.columns = ["Text"]
print(test_spam1.head())

In [ ]:
text_cleaning = lambda x: text_cleaning_chinese(x)
test_ham1['Cleaned_Text'] = pd.DataFrame(test_ham1['Text'].apply(text_cleaning))
test_spam1['Cleaned_Text'] = pd.DataFrame(test_spam1['Text'].apply(text_cleaning))

In [ ]:
pred_data = svm_model.predict(test_ham1['Cleaned_Text'])
test_ham1['Predicted'] = pred_data
test_ham1['Predicted'].value_counts()

In [ ]:
pred_data = svm_model.predict(test_spam1['Cleaned_Text'])
test_spam1['Predicted'] = pred_data
test_spam1['Predicted'].value_counts()