In [1]:
import pandas as pd 
import numpy as np
# 1 spam, 0 ham

In [2]:
# spam data english
spam_data1 = pd.read_csv('category/spam_data_lg.csv')
spam_data1.columns
print(len(spam_data1))

57534


In [3]:
spam_data1 = spam_data1.dropna(axis = 0, how ='any')
len(spam_data1)

57528

In [4]:
spam_data1 = spam_data1.drop(['Unnamed: 0'],axis=1)
spam_data1.columns

Index(['Text', 'Label[Spam/Non-Spam]'], dtype='object')

In [5]:
spam_data1.rename(columns = {'Label[Spam/Non-Spam]': 'Category'}, inplace = True)
print(spam_data1.head())
print(len(spam_data1))

                                                Text  Category
0              That just seriously ruined my night..       0.0
1  @JessleaC I no they are so funny ..! I love yo...       0.0
2  @honkwas might drive so we could go subway or ...       0.0
3  That @brad_frost post is bourne out by my expe...       0.0
4       why tf do i keep waking up every 2 hours -.-       0.0
57528


In [6]:
spam_data1['Category'] = spam_data1['Category'].astype(int)
spam_data1.head()

Text  Category
0              That just seriously ruined my night..         0
1  @JessleaC I no they are so funny ..! I love yo...         0
2  @honkwas might drive so we could go subway or ...         0
3  That @brad_frost post is bourne out by my expe...         0
4       why tf do i keep waking up every 2 hours -.-         0

In [7]:
# spam data malay
spam_data2 = pd.read_csv('category/spam_data_indon.csv')
spam_data2.columns
print(len(spam_data2))

1143


In [8]:
spam_data2 = spam_data2.dropna(axis = 0, how ='any')
len(spam_data2)

1143

In [9]:
spam_data2.columns

Index(['Teks', 'label'], dtype='object')

In [10]:
spam_data2.rename(columns = {'Teks': 'Text', 'label': 'Category'}, inplace = True)
print(spam_data2.head())
print(len(spam_data2))

                                                Text Category
0  [PROMO] Beli paket Flash mulai 1GB di MY TELKO...    promo
1  2.5 GB/30 hari hanya Rp 35 Ribu Spesial buat A...    promo
2  2016-07-08 11:47:11.Plg Yth, sisa kuota Flash ...    promo
3  2016-08-07 11:29:47.Plg Yth, sisa kuota Flash ...    promo
4  4.5GB/30 hari hanya Rp 55 Ribu Spesial buat an...    promo
1143


In [11]:
spam_data2['Category'].value_counts()

normal      569
penipuan    335
promo       239
Name: Category, dtype: int64

In [12]:
spam_data2.loc[spam_data2['Category'] == 'promo', 'Category'] = 1
spam_data2.loc[spam_data2['Category'] == 'penipuan', 'Category'] = 1
spam_data2.loc[spam_data2['Category'] == 'normal', 'Category'] = 0

In [13]:
spam_data2['Category'] = spam_data2['Category'].astype(int)
spam_data2.head()

Text  Category
0  [PROMO] Beli paket Flash mulai 1GB di MY TELKO...         1
1  2.5 GB/30 hari hanya Rp 35 Ribu Spesial buat A...         1
2  2016-07-08 11:47:11.Plg Yth, sisa kuota Flash ...         1
3  2016-08-07 11:29:47.Plg Yth, sisa kuota Flash ...         1
4  4.5GB/30 hari hanya Rp 55 Ribu Spesial buat an...         1

In [14]:
# spam data chinese
spam_data3 = pd.read_csv('category/spam_data_chinese_sm.csv')
print(spam_data3.head())
print(len(spam_data3))

                                                Text  Category
0                          便 宜 又 适 用 ， 也 非 常 容 易 撕 掉         0
1  质 量 跟 我 预 想 的 差 不 多 ， 布 料 很 薄 ， 说 不 上 有 没 有 色 ...         0
2                    好 评 应 该 有 八 十 五 字 了 吧 ， 涨 淘 气 值         0
3                          第 二 双 ， 超 级 棒 ， 上 脚 很 好 看         0
4                差 ， 去 日 本 无 服 务 ， 耽 误 了 一 天 半 时 间 呵         0
37297


In [15]:
spam_data3['Category'] = spam_data3['Category'].astype(int)
spam_data3.head()

Text  Category
0                          便 宜 又 适 用 ， 也 非 常 容 易 撕 掉         0
1  质 量 跟 我 预 想 的 差 不 多 ， 布 料 很 薄 ， 说 不 上 有 没 有 色 ...         0
2                    好 评 应 该 有 八 十 五 字 了 吧 ， 涨 淘 气 值         0
3                          第 二 双 ， 超 级 棒 ， 上 脚 很 好 看         0
4                差 ， 去 日 本 无 服 务 ， 耽 误 了 一 天 半 时 间 呵         0

In [16]:
# Combine all dataframes into one master dataframe
spam_data = pd.concat([spam_data1, spam_data2], ignore_index = True)
print(spam_data.head())
print(len(spam_data))

                                                Text  Category
0              That just seriously ruined my night..         0
1  @JessleaC I no they are so funny ..! I love yo...         0
2  @honkwas might drive so we could go subway or ...         0
3  That @brad_frost post is bourne out by my expe...         0
4       why tf do i keep waking up every 2 hours -.-         0
58671


In [17]:
# spam_data = spam_data1.copy()

In [18]:
# # spam data
# spam_data2 = pd.read_csv('category/spam_data.csv')
# spam_data2.columns
# print(len(spam_data2))

In [19]:
# spam_data2 = spam_data2.dropna(axis = 0, how ='any')
# len(spam_data2)

In [20]:
# spam_data2.rename(columns = {'Message': 'Text'}, inplace = True)
# print(spam_data2.head())
# print(len(spam_data2))

In [21]:
# spam_data2.loc[spam_data2['Category'] == 'spam', 'Category'] = 1
# spam_data2.loc[spam_data2['Category'] == 'ham', 'Category'] = 0
# spam_data2.head()

In [22]:
# spam_data2['Category'] = spam_data2['Category'].astype(int)

In [23]:
# #Combine all dataframes into one master dataframe
# spam_data = pd.concat([spam_data1, spam_data2], ignore_index = True)
# print(spam_data.head())
# print(len(spam_data))

In [24]:
# ## Drop missing value
# spam_data = spam_data.dropna(axis = 0, how ='any')
# len(spam_data)

In [25]:
# spam_data['Category'] = spam_data['Category'].astype(int)

In [26]:
spam_data['Category'].value_counts()

0    45757
1    12914
Name: Category, dtype: int64

In [27]:
# from spacy.lang.en.stop_words import STOP_WORDS
import stopwordsiso as sw
from collections import Counter
import string
import spacy
import re

punctuation_auto = list(string.punctuation)
punctuation_custom = [ '...', '…' ]
punctuation = np.unique(punctuation_auto+punctuation_custom)

stop_words = list(sw.stopwords(["ms", "id","zh","en"]))
stop_words_custom = ['kau', 'yg', 'mcm', 'gak', 'nak', 'ni', 'tu', 'la', 'je', 'kat', 'ya', 'dgn', 'tau', 'org', 'rt', 'aja', 'nk', 'dah',
                        'orang', 'sy', 'ga', 'kalo', 'kena']
STOP_WORDS = np.unique(stop_words+stop_words_custom)

def light_text_cleaning_english(text):
    text = text.lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\w*\d\w*', '', text)
    text = re.sub('[‘’“”…]', '', text)
    text = re.sub('\n', '', text)

    # remove numbers
    text = re.sub(r'\d+', '', text)
    # remove links
    text = re.sub('http[s]?://\S+', '', text)
    # remove word with tweethandle @name
    text = re.sub('[^ ]*@[^ ]*', '', text)

    return text

# def text_cleaning_english(text,mynlp):

#     # remove numbers
#     text = re.sub(r'\d+', '', text)
#     # remove links
#     text = re.sub('http[s]?://\S+', '', text)
#     # remove word with tweethandle @name
#     text = re.sub('[^ ]*@[^ ]*', '', text)

#     doc = mynlp(text)
    
#     # Lemmatization
#     tokens = []
#     for token in doc:
#         if token.lemma_ != "-PRON-":
#             temp = token.lemma_.lower().strip()
#         else:
#             temp = token.lower_
#         tokens.append(temp)
    
#     # Remove punctuation and stopwords
#     cleaned_tokens = []
#     for token in tokens:
#         if token not in list(STOP_WORDS) and token not in punctuation:
#             cleaned_tokens.append(token)

#     # traverse in the string     
#     complete_sentence = ' '.join([str(words) for words in cleaned_tokens])

#     return complete_sentence

def most_used_words(data,str_input):

    words_list = []
    temp = []
    for index, row in data.iterrows():
        # print(type(row['cleaned_'+str_input]))
        tokens = str(row['Cleaned_'+str_input]).split() 
        for word in tokens:
            if word not in list(STOP_WORDS):
                words_list.append(word)

    common_words = Counter(words_list).most_common(50)
    for key, value in common_words:
        temp.append({'name': key, 'value': value})

    return temp

In [28]:
text_cleaning = lambda x: light_text_cleaning_english(x)
spam_data['Cleaned_Text'] = pd.DataFrame(spam_data['Text'].apply(text_cleaning))

In [29]:
# # get common words in data
# word_list = most_used_words(spam_data,'Text')
# print(word_list)

In [30]:
# SPLIT TRAINING & TESTING DATA
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(spam_data['Cleaned_Text'],spam_data['Category'],test_size=0.2,shuffle=True, random_state=42)
print(X_train.shape, y_train.shape)

(46936,) (46936,)


In [31]:
X_train.head()

42194    i have cottage on my island now my island is e...
354      rt strommark  word lead emerged from medieval ...
30891    boot up google now v iphone pirate bay sets sa...
21221                mom what did you learn in apush today
13719    its a brutal experience to try and change the ...
Name: Cleaned_Text, dtype: object

In [32]:
y_train.head()

42194    1
354      0
30891    0
21221    0
13719    1
Name: Category, dtype: int32

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC 
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score, precision_score, f1_score, recall_score

def sentiment_pipeline(data_train_input,data_train_target,model_type):
    # Classifier selection
    if model_type == "linear":
        classifier = LinearSVC()
    elif model_type == "logistic":
        classifier = LogisticRegression(max_iter=1000)
    elif model_type == "sgd":
        classifier = SGDClassifier()
    elif model_type == "naive_bayes":
        classifier = MultinomialNB()
    elif model_type == "xgboost":
        classifier = XGBClassifier(use_label_encoder=False,eta=0.1,gamma=0.3, n_estimators=100, learning_rate=0.5, min_child_weight=5, 
        max_depth=5, colsample_bytree=0.7,objective="binary:logistic", eval_metric="logloss",verbosity=0)

    tfidf = TfidfVectorizer()

    # Pipeline setup
    clf = Pipeline([('tfidf', tfidf), ('clf', classifier)])

    model = clf.fit(data_train_input,data_train_target)

    return model

def sentiment_model_predict(model,data_test_input,data_test_target):
    data_prediction=model.predict(data_test_input)
    conf_matrix = confusion_matrix(data_test_target,data_prediction)
    acc_score = accuracy_score(data_test_target, data_prediction)
    pre_score = precision_score(data_test_target, data_prediction, average="macro")
    re_score = recall_score(data_test_target, data_prediction, average="macro")
    f_score = f1_score(data_test_target, data_prediction, average="macro")

    print("Accuracy : "+str(round(acc_score*100,2)))
    print("Precision : "+str(round(pre_score*100,2)))
    print("Recall : "+str(round(re_score*100,2)))
    print("F1-Score :"+str(round(f_score*100,2)))
    print(conf_matrix)

In [34]:
# Support Vector Classification
svm_model = sentiment_pipeline(X_train, y_train, 'linear')
sentiment_model_predict(svm_model,X_test,y_test)

Accuracy : 93.42
Precision : 92.43
Recall : 87.48
F1-Score :89.65
[[9023  195]
 [ 577 1940]]


In [35]:
# test_data1 = pd.read_csv('category/spam_test.txt', delimiter= '\t')
# test_data1.columns = ["Text"]
# print(test_data1.head())
# print(len(test_data1))

# test_data2 = pd.read_csv('category/ham_test.txt', delimiter= '\t')
# test_data2.columns = ["Text"]
# print(test_data2.head())
# print(len(test_data2))

In [36]:
# text_cleaning = lambda x: light_text_cleaning_english(x)
# test_data1['Cleaned_Text'] = pd.DataFrame(test_data1['Text'].apply(text_cleaning))
# test_data2['Cleaned_Text'] = pd.DataFrame(test_data2['Text'].apply(text_cleaning))

In [37]:
# pred_data=svm_model.predict(test_data1['Cleaned_Text'])
# test_data1['Predicted'] = pred_data
# test_data1['Predicted'].value_counts()

In [38]:
# pred_data=svm_model.predict(test_data2['Cleaned_Text'])
# test_data2['Predicted'] = pred_data
# test_data2['Predicted'].value_counts()

In [39]:
# Logistic Regression
lr_model = sentiment_pipeline(X_train, y_train, 'logistic')
sentiment_model_predict(lr_model,X_test,y_test)

Accuracy : 91.9
Precision : 92.57
Recall : 82.78
F1-Score :86.5
[[9102  116]
 [ 835 1682]]


In [40]:
# Stochastic Gradient Descent
sgd_model = sentiment_pipeline(X_train, y_train, 'sgd')
sentiment_model_predict(sgd_model,X_test,y_test)

Accuracy : 90.79
Precision : 92.85
Recall : 79.51
F1-Score :83.99
[[9150   68]
 [1013 1504]]


In [41]:
# Multinomial Naive Bayes
nb_model = sentiment_pipeline(X_train, y_train, 'naive_bayes')
sentiment_model_predict(nb_model,X_test,y_test)

Accuracy : 88.2
Precision : 92.54
Recall : 72.83
F1-Score :77.77
[[9194   24]
 [1361 1156]]


In [42]:
# Xgboost
# multi:softprob/multi:softmax for multi class and binary:logistic for binary
xg_model = sentiment_pipeline(X_train, y_train, 'xgboost')
sentiment_model_predict(xg_model,X_test,y_test)

Accuracy : 90.88
Precision : 91.02
Recall : 80.97
F1-Score :84.69
[[9064  154]
 [ 916 1601]]


In [43]:
# import joblib

# # save model
# joblib_file_svm = "linear_pretrained_multi_spam_model.pkl"  
# joblib.dump(svm_model, joblib_file_svm)

In [44]:
# # load model
# joblib_SVM_model = joblib.load(joblib_file_svm)
# sentiment_model_predict(joblib_SVM_model,X_test,y_test)

In [45]:
# print(spam_data.loc[spam_data['Category'] == 1])